### ISSUE TITLE
menu con "s"

### ISSUE THREAD

**Issue by ViruX** [ViruX/jcc-django#4]
los menú del admin algunos tienen agregados de "s" al final, puede llegar a ser un problema del template

**Comment by juaniscarafia** [comment]
Yo eso ya lo vi, y mire el código, pero creo que es el suite del admin que agregamos que le agrega las  "s" al menú.

**Comment by fproldan** [comment]
El problema no es template, es que no tiene configurado verbese_name_plural en ningun model, por defecto agrega "s", si por ejemplo el modelo se llama cancion en admin pone cancions, por lo tanto tienen que configurarlo explicito para que diga canciones por ejemplo.

Documentación: https://docs.djangoproject.com/en/1.7/ref/models/options/#verbose-name-plural
